try {
	throw Error("Error");
} catch (e) {
	debugger;
}