try {
	throw "Error";
} finally {
    
} finally {
    
}